name: Build and Deploy Code 

on: [push, pull_requests]

jobs:
  job1: 
    runs-on: ubuntu-latest 
    steps: 
      - name: pulling git repo 
        uses: actions/checkout@v4
      - name: say hi to Yazmin 
        run: echo "hello Yazmin"
        